spring:
  cloud:
    gcp:
      core:
        enabled: false
      secretmanager:
        enabled: false
      sql:
        enabled: false

  datasource:
    url: jdbc:mysql://localhost:3306/gradebook
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 2MB

cors:
  allowedOriginPattern: http://localhost:5173

gcp:
  bucket:
    name: test-bucket
  pubsub:
    project-id: your-project-id
    topic-id: test-topic
